import PageContainer from "@/components/pageContainer";
import { RegularH1, StyledH2 } from "@/components/styledComponents";
import { PortfolioData } from "@/static/type";
import { AppTheme } from "@/styles/theme";
import { getLocalData } from "@/utils/getLocalData";
import { GetStaticProps } from "next";
import Head from "next/head";

type Props = {
  content: PortfolioData;
};

const Home = ({ content }: Props) => {
  return (
    <>
      <Head>
        <title>{content.common.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageContainer index={0} background={AppTheme.colors["bg-home"]}>
        <RegularH1>{content.home.title}</RegularH1>
        <StyledH2>{content.home.subtitle}</StyledH2>
      </PageContainer>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const content: PortfolioData = await getLocalData();

  return {
    props: {
      content,
    },
  };
};

export default Home;
