import PageContainer from "@/components/pageContainer";
import { RegularH1, StyledH2 } from "@/components/styledComponents";
import { AppTheme } from "@/styles/theme";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>{`Xiao's Portfolio`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageContainer index={0} background={AppTheme.colors["bg-home"]}>
        <RegularH1>{`Hi, I'm Xiao`}</RegularH1>
        <StyledH2>Web Engineer, Front-End Addict.</StyledH2>
      </PageContainer>
    </>
  );
}
